//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagen
    {
        public int id { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public string nombre_imagen { get; set; }
        public string formato { get; set; }
    
        public virtual pregunta pregunta { get; set; }
    }
}
