//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pregunta()
        {
            this.alternativa = new HashSet<alternativa>();
            this.imagen = new HashSet<imagen>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_tipo_pregunta { get; set; }
        public string descripcion_pregunta { get; set; }
        public string comentario { get; set; }
        public bool alternativas_aleatorias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alternativa> alternativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagen> imagen { get; set; }
        public virtual tipo_pregunta tipo_pregunta { get; set; }
    }
}
